"""Abuse-report generator: turn a verdict into a ready-to-send takedown report.

A verdict is only useful if someone acts on it. This module renders a
markdown report with the indicators of compromise, the cited evidence,
and suggested abuse contacts — copy/paste ready for a registrar, hosting
provider, or brand-protection team.
"""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone

_DOMAIN_RE = re.compile(r"\b(?:[a-z0-9-]+\.)+[a-z]{2,}\b", re.IGNORECASE)


def _registrable(domain: str) -> str:
    parts = domain.lower().strip(".").split(".")
    return ".".join(parts[-2:]) if len(parts) >= 2 else domain.lower()


def extract_domains(*texts: str) -> list[str]:
    """Pull candidate domains out of free-text evidence fields."""
    out: list[str] = []
    for t in texts:
        for m in _DOMAIN_RE.findall(t or ""):
            d = _registrable(m)
            if d not in out:
                out.append(d)
    return out


def suggested_recipients(domains: list[str]) -> list[str]:
    """Conventional abuse contacts: abuse@ and security@ per registrable domain."""
    out: list[str] = []
    for d in domains:
        for local in ("abuse", "security"):
            addr = f"{local}@{d}"
            if addr not in out:
                out.append(addr)
    return out


def build_abuse_report(email_id: str, verdict: dict,
                       infra: dict[str, list[str]] | None = None) -> str:
    """Render the markdown takedown report for one verdict.

    `verdict` is the RAW (unredacted) store row — an abuse report with
    masked addresses is useless. `infra` maps node-type -> values, taken
    from the threat graph (domain:/url:/sender:/ip:/phone: neighbors).
    """
    infra = infra or {}
    label = (verdict.get("label") or "unknown").upper()
    score = verdict.get("score", 0)
    conf = verdict.get("confidence", 0)
    sender = verdict.get("sender") or "(unknown)"
    received = verdict.get("received_at") or "(unknown)"

    flags = verdict.get("red_flags") or []
    if isinstance(flags, str):
        flags = json.loads(flags)
    det = verdict.get("det_signals") or []
    if isinstance(det, str):
        det = json.loads(det)

    # Indicators: graph first (structured), evidence text as backfill.
    domains = list(infra.get("domain", []))
    urls = list(infra.get("url", []))
    ips = list(infra.get("ip", []))
    phones = list(infra.get("phone", []))
    evidence_text = " ".join(
        str(f.get("detail", "")) + " " + str(f.get("evidence", ""))
        for f in list(flags) + list(det))
    for d in extract_domains(evidence_text, sender,
                             " ".join(urls), verdict.get("campaign_note", "")):
        if d not in domains:
            domains.append(d)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    L = [
        f"# AEGIS abuse report — `{email_id}`",
        f"_Generated {now} · verdict **{label}** "
        f"(score {score:.2f}, confidence {conf:.0%})_",
        "",
        "## Summary",
        f"A message from `{sender}` received {received} was analyzed by "
        f"AEGIS and flagged **{label}**. The indicators and evidence below "
        "are cited from the analysis; every claim links to the artifact "
        "it came from.",
        "",
        "## Indicators of compromise",
        f"- **Sender:** `{sender}`",
    ]
    for d in domains:
        L.append(f"- **Domain:** `{d}`")
    for u in urls[:10]:
        L.append(f"- **URL:** `{u}`")
    for ip in ips:
        L.append(f"- **IP:** `{ip}`")
    for ph in phones:
        L.append(f"- **Phone:** `{ph}`")
    if not (domains or urls or ips or phones):
        L.append("- _(no network indicators extracted)_")
    L += ["", "## Evidence"]
    for f in flags[:8]:
        L.append(f"- **{f.get('title', '')}** — _{f.get('evidence', '')}_")
    for s in det:
        if s.get("severity") == "high":
            L.append(f"- **[{s.get('name', '')}]** {s.get('detail', '')} "
                     f"— _{s.get('evidence', '')}_")
    if not flags and not det:
        L.append("- _(no high-severity findings recorded)_")
    campaign = verdict.get("campaign_note") or ""
    if campaign:
        L += ["", "## Campaign linkage", campaign]
    L += ["", "## Suggested recipients",
          "Conventional abuse contacts for the domains above "
          "(verify via WHOIS/RDAP before sending):", ""]
    recips = suggested_recipients(domains)
    if recips:
        L += [f"- `{r}`" for r in recips]
    else:
        L.append("- _(no domains to derive contacts from)_")
    L += ["",
          "---",
          "_Report generated by AEGIS. Evidence excerpts are quoted from "
          "the analyzed message; handle according to your disclosure "
          "policy._"]
    return "\n".join(L)
