"""Turn a verdict into a copy-paste takedown report for registrars, hosts and
brand-protection teams: indicators of compromise plus the cited evidence."""
from __future__ import annotations

from datetime import datetime, timezone


def _registrable(domain: str) -> str:
    parts = domain.lower().strip(".").split(".")
    return ".".join(parts[-2:]) if len(parts) >= 2 else domain.lower()


def build(detail: dict) -> str:
    v = detail.get("verdict") or {}
    triage = detail.get("triage") or {}
    email = detail.get("email") or {}
    label = (v.get("label") or detail.get("label") or "UNKNOWN").replace("_", " ")
    domains = list(dict.fromkeys(_registrable(d) for d in triage.get("domains", []) if d))
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    L = [f"# AEGIS abuse report: {detail.get('id')}",
         f"_Generated {now}. Verdict **{label}** (score {v.get('score', 0):.2f})._", "",
         "## Summary",
         f"A message from `{email.get('from') or '(unknown sender)'}` with subject "
         f"\"{email.get('subject', '')}\" was analyzed by AEGIS and flagged {label}. "
         "Every item below is quoted from the analyzed message.", "",
         "## Indicators of compromise",
         f"- Sender: `{email.get('from') or '(unknown)'}`"]
    if email.get("reply_to"):
        L.append(f"- Reply-To: `{email['reply_to']}`")
    L += [f"- Domain: `{d}`" for d in domains]
    L += [f"- URL: `{u}`" for u in triage.get("urls", [])[:10]]
    L += [f"- Phone: `{p}`" for p in triage.get("phone_numbers", [])[:5]]
    L += ["", "## Evidence"]
    flags = detail.get("red_flags") or []
    L += [f"- **{f['title']}**: _{f['evidence']}_" for f in flags]
    if not flags:
        L.append("- (no high-severity findings recorded)")
    note = (detail.get("campaign") or {}).get("note")
    if note:
        L += ["", "## Campaign linkage", note]
    L += ["", "## Suggested recipients",
          "Conventional abuse contacts (verify with WHOIS/RDAP before sending):", ""]
    L += [f"- `abuse@{d}`" for d in domains] or ["- (no domains found)"]
    L += ["", "Also report to: reportphishing@apwg.org, and in the US reportfraud.ftc.gov.",
          "", "---", "_Generated by AEGIS._"]
    return "\n".join(L)
